/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface BitEstateInterface extends Interface {
  getFunction(
    nameOrSignature: "buyProperty" | "listProperty" | "properties"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PropertyListed" | "PropertySold"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyProperty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listProperty",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "properties",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "buyProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "properties", data: BytesLike): Result;
}

export namespace PropertyListedEvent {
  export type InputTuple = [
    propertyId: BigNumberish,
    owner: AddressLike,
    price: BigNumberish,
    metadataURI: string
  ];
  export type OutputTuple = [
    propertyId: bigint,
    owner: string,
    price: bigint,
    metadataURI: string
  ];
  export interface OutputObject {
    propertyId: bigint;
    owner: string;
    price: bigint;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PropertySoldEvent {
  export type InputTuple = [
    propertyId: BigNumberish,
    oldOwner: AddressLike,
    newOwner: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: bigint,
    oldOwner: string,
    newOwner: string,
    price: bigint
  ];
  export interface OutputObject {
    propertyId: bigint;
    oldOwner: string;
    newOwner: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BitEstate extends BaseContract {
  connect(runner?: ContractRunner | null): BitEstate;
  waitForDeployment(): Promise<this>;

  interface: BitEstateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyProperty: TypedContractMethod<
    [propertyId: BigNumberish],
    [void],
    "payable"
  >;

  listProperty: TypedContractMethod<
    [price: BigNumberish, metadataURI: string],
    [bigint],
    "nonpayable"
  >;

  properties: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, string, boolean] & {
        id: bigint;
        owner: string;
        price: bigint;
        metadataURI: string;
        isListed: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyProperty"
  ): TypedContractMethod<[propertyId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "listProperty"
  ): TypedContractMethod<
    [price: BigNumberish, metadataURI: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "properties"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, string, boolean] & {
        id: bigint;
        owner: string;
        price: bigint;
        metadataURI: string;
        isListed: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "PropertyListed"
  ): TypedContractEvent<
    PropertyListedEvent.InputTuple,
    PropertyListedEvent.OutputTuple,
    PropertyListedEvent.OutputObject
  >;
  getEvent(
    key: "PropertySold"
  ): TypedContractEvent<
    PropertySoldEvent.InputTuple,
    PropertySoldEvent.OutputTuple,
    PropertySoldEvent.OutputObject
  >;

  filters: {
    "PropertyListed(uint256,address,uint256,string)": TypedContractEvent<
      PropertyListedEvent.InputTuple,
      PropertyListedEvent.OutputTuple,
      PropertyListedEvent.OutputObject
    >;
    PropertyListed: TypedContractEvent<
      PropertyListedEvent.InputTuple,
      PropertyListedEvent.OutputTuple,
      PropertyListedEvent.OutputObject
    >;

    "PropertySold(uint256,address,address,uint256)": TypedContractEvent<
      PropertySoldEvent.InputTuple,
      PropertySoldEvent.OutputTuple,
      PropertySoldEvent.OutputObject
    >;
    PropertySold: TypedContractEvent<
      PropertySoldEvent.InputTuple,
      PropertySoldEvent.OutputTuple,
      PropertySoldEvent.OutputObject
    >;
  };
}
