/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BitEstate } from "./BitEstate";
export * as factories from "./factories";
export { BitEstate__factory } from "./factories/BitEstate__factory";
